### PR TITLE
Reporter setup

### PR DESCRIPTION
**Pull request by jalvar53**
Creating reporter instance and configuring it for the project.

wait merge the pull: https://github.com/jalvar53/protractor-workshop-2017/pull/3

### CODE REVIEW

**Comment by jalvar53** [comment]
reporter

Reporter working

**Review by luisbolanoss — COMMENTED** [review]
👍  LGTM

**Review by luisbolanoss — COMMENTED** [review]
👍  LGTM

**Review by luisbolanoss — APPROVED** [review]
👍

**Pull request merged**
